ДЗ к лекции №9 - Terraform 2
Otus-DevOps-2021-11/zakharovaaa_infra pull request #6
Opened 2022-01-14 19:40 UTC by zakharovaaa

# Выполнено ДЗ к лекции №9

 - [ ] Основное ДЗ
"Параметризируйте конфигурацию модулей насколько считаете нужным"

## В процессе сделано:
 - Пункт 1
с помощью Packer созданы два новых образа для сервера БД и сервера приложения.
 - Пункт 2
с помощью модулей Terraform создано 2 ВМ в Yandex Cloud: сервер БД и сервер приложения; и два окружения stage и prod.
 - Пункт 3
модули параметризированы.

2022-01-16 15:24 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Вам стоит проверить модули терраформа и пути до них =)

2022-01-17 06:25 UTC, zakharovaaa commented
> 

Доброе утро! полностью согласна, что ошибка в тестах ругается на путь к модулям, но как уже писала в блоке в сообщениях к ДЗ на сайте отуса, не понимаю, почему такая ошибка с путями к модулям не возникает у меня при создании ВМ (или какая либо другая)) - свежесозданные две минуты назад из окружения stage 
PS C:\Users\Alina\Documents\otus-devops\zakharovaaa_infra\terraform\stage> terraform apply
...
external_ip_address_app = 51.250.21.77
external_ip_address_db = 62.84.124.1
машины не удаляла - можно проверить их доступность.
подскажите, пожалуйста, что упускаю или как теперь ломать окружение чтобы тесты прошли?)

2022-01-18 08:31 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу
Давайте постараемся починить =)

2022-01-18 08:31 UTC, mrgreyves commented on terraform/storage-bucket.tf
> +  source          = "../modules/app"
Вот тут ошибка =)
То есть, когда терраформ проверяет этот файл он естественно пытается использовать модули по путям
И выходит в дереве директорий на уровень выше, а на уровне выше их конечно же нет =)
Вот тут можно подкорректировать =)

2022-01-18 09:27 UTC, zakharovaaa commented on terraform/storage-bucket.tf
> +  source          = "../modules/app"
спасибо! виновата, надо было файл-пустышку делать всё-таки пустышкой сразу

2022-01-18 19:31 UTC, mrgreyves approved these changes
Вот теперь точно апрув =)

2022-01-19 05:13 UTC, merged